using System.Collections.Generic;

namespace EmojiSense
{
    internal static class Emojis
    {
        public static Dictionary<string, string> People = new()
        {
            {":alien:","👽"},
            {":angel:","👼"},
            {":anger:","💢"},
            {":angry:","😠"},
            {":anguished:","😧"},
            {":astonished:","😲"},
            {":baby:","👶"},
            {":blue heart:","💙"},
            {":blush:","😊"},
            {":boom:","💥"},
            {":bow:","🙇"},
            {":boy:","👦"},
            {":breast-feeding:","🤱"},
            {":bride with veil:","👰"},
            {":broken heart:","💔"},
            {":bust in silhouette:","👤"},
            {":busts in silhouette:","👥"},
            {":call me hand:","🤙"},
            {":clap:","👏"},
            {":cold face:","🥶"},
            {":cold sweat:","😰"},
            {":collision:","💥"},
            {":confounded:","😖"},
            {":confused:","😕"},
            {":construction worker:","👷"},
            {":cop:","👮"},
            {":couple with heart:","💑"},
            {":couple:","👫"},
            {":couplekiss:","💏"},
            {":cowboy hat face:","🤠"},
            {":crossed fingers:","🤞"},
            {":cry:","😢"},
            {":crying cat face:","😿"},
            {":cupid:","💘"},
            {":dancer:","💃"},
            {":dancers:","👯"},
            {":dash:","💨"},
            {":deaf person:","🧏"},
            {":disappointed relieved:","😥"},
            {":disappointed:","😞"},
            {":disguised face:","🥸"},
            {":dizzy face:","😵"},
            {":dizzy:","💫"},
            {":droplet:","💧"},
            {":ear:","👂"},
            {":exclamation:","❗"},
            {":expressionless:","😑"},
            {":eye:","👁️"},
            {":eyes:","👀"},
            {":face holding back tears:","🥹"},
            {":face with bags under eyes:","🫩"},
            {":face with monocle:","🧐"},
            {":face with raised eyebrow:","🤨"},
            {":face with rolling eyes:","🙄"},
            {":facepunch:","👊"},
            {":family:","👪"},
            {":fearful:","😨"},
            {":feet:","🐾"},
            {":fingerprint:","🫆"},
            {":fire:","🔥"},
            {":fist:","✊"},
            {":flushed:","😳"}, 
            {":frowning:","😦"},
            {":frowning face:","☹️"},
            {":fu:","🖕"},
            {":girl:","👧"},
            {":green heart:","💚"},
            {":grey exclamation:","❕"},
            {":grey question:","❔"},
            {":grimacing:","😬"},
            {":grin:","😁"},
            {":grinning:","😀"},
            {":guardsman:","💂"},
            {":haircut:","💇"},
            {":hand:","✋"},
            {":hand with fingers splayed:","🖐️"},
            {":hand with index finger and thumb crossed:","🫰"},
            {":hankey:","💩"},
            {":hear no evil:","🙉"},
            {":heart eyes cat:","😻"},
            {":heart eyes:","😍"},
            {":heart:","❤"},
            {":heart hands:","🫶"},
            {":heartbeat:","💓"},
            {":heartpulse:","💗"},
            {":hushed:","😯"},
            {":imp:","👿"},
            {":information desk person:","💁"},
            {":innocent:","😇"},
            {":japanese goblin:","👺"},
            {":japanese ogre:","👹"},
            {":joy cat:","😹"},
            {":joy:","😂"},
            {":kiss:","💋"},
            {":kissing cat:","😽"},
            {":kissing closed eyes:","😚"},
            {":kissing heart:","😘"},
            {":kissing smiling eyes:","😙"},
            {":kissing:","😗"},
            {":laughing:","😆"},
            {":leftwards pushing hand:","🫷"},
            {":lips:","👄"},
            {":love letter:","💌"},
            {":love-you gesture:","🤟"},
            {":man dancing:","🕺"},
            {":man with gua pi mao:","👲"},
            {":man with turban:","👳"},
            {":man:","👨"},
            {":mask:","😷"},
            {":massage:","💆"},
            {":mechanical leg:","🦿"},
            {":melting face:","🫠"},
            {":metal:","🤘"},
            {":muscle:","💪"},
            {":musical note:","🎵"},
            {":nail care:","💅"},
            {":neutral face:","😐"},
            {":ninja:","🥷"},
            {":no good:","🙅"},
            {":no mouth:","😶"},
            {":nose:","👃"},
            {":notes:","🎶"},
            {":ok hand:","👌"},
            {":ok woman:","🙆"},
            {":older man:","👴"},
            {":older woman:","👵"},
            {":open hands:","👐"},
            {":open mouth:","😮"},
            {":palms up together:","🤲"},
            {":pensive:","😔"},
            {":people hugging:","🫂"},
            {":persevere:","😣"},
            {":person bouncing ball:","⛹️"},
            {":person fencing:","🤺"},
            {":person in bed:","🛌"},
            {":person lifting weights:","🏋️"},
            {":person playing handball:","🤾"},
            {":person standing:","🧍"},
            {":person with crown:","🫅"},
            {":pinched fingers:","🤌"},
            {":pinching hand:","🤏"},
            {":pleading face:","🥺"},
            {":point down:","👇"},
            {":point left:","👈"},
            {":point right:","👉"},
            {":point up 2:","👆"},
            {":point up:","☝"},
            {":poop:","💩"},
            {":pouting cat:","😾"},
            {":pray:","🙏"},
            {":pregnant man:","🫃"},
            {":pregnant woman:","🤰"},
            {":princess:","👸"},
            {":punch:","👊"},
            {":purple heart:","💜"},
            {":question:","❓"},
            {":rage:","😡"},
            {":raised hand:","✋"},
            {":raised hands:","🙌"},
            {":raising hand:","🙋"},
            {":relaxed:","☺"},
            {":relieved:","😌"},
            {":revolving hearts:","💞"},
            {":rightwards pushing hand:","🫸"},
            {":running:","🏃"},
            {":satisfied:","😆"},
            {":scream cat:","🙀"},
            {":scream:","😱"},
            {":see no evil:","🙈"},
            {":selfie:","🤳"},
            {":shaking face:","🫨"},
            {":shit:","💩"},
            {":skull:","💀"},
            {":skull and crossbones:","☠️"},
            {":sleeping:","😴"},
            {":sleepy:","😪"},
            {":slightly frowning face:","🙁"},
            {":smile cat:","😸"},
            {":smile:","😄"},
            {":smiley cat:","😺"},
            {":smiley:","😃"},
            {":smiling face with hearts:","🥰"},
            {":smiling face with tear:","🥲"},
            {":smiling imp:","😈"},
            {":smirk cat:","😼"},
            {":smirk:","😏"},
            {":sneezing face:","🤧"},
            {":sob:","😭"},
            {":sparkles:","✨"},
            {":sparkling heart:","💖"},
            {":speak no evil:","🙊"},
            {":speech balloon:","💬"},
            {":star:","⭐"},
            {":star2:","🌟"},
            {":stuck out tongue closed eyes:","😝"},
            {":stuck out tongue winking eye:","😜"},
            {":stuck out tongue:","😛"},
            {":sunglasses:","😎"},
            {":supervillain:","🦹"},
            {":sweat drops:","💦"},
            {":sweat smile:","😅"},
            {":sweat:","😓"},
            {":thought balloon:","💭"},
            {":thumbsdown:","👎"},
            {":thumbsup:","👍"},
            {":tired face:","😫"},
            {":tongue:","👅"},
            {":triumph:","😤"},
            {":troll:","🧌"},
            {":two hearts:","💕"},
            {":two men holding hands:","👬"},
            {":two women holding hands:","👭"},
            {":unamused:","😒"},
            {":v:","✌"},
            {":vulcan salute:","🖖"},
            {":walking:","🚶"},
            {":wave:","👋"},
            {":weary:","😩"},
            {":wind face:","🌬️"},
            {":wink:","😉"},
            {":woman:","👩"},
            {":worried:","😟"},
            {":writing hand:","✍️"},
            {":yawning face:","🥱"},
            {":yellow heart:","💛"},
            {":yum:","😋"},
            {":zipper-mouth face:","🤐"},
            {":zzz:","💤"},
        };

        public static Dictionary<string, string> Nature = new() 
        {
            {":ant:","🐜"},
            {":baby chick:","🐤"},
            {":bear:","🐻"},
            {":beaver:","🦫"},
            {":beetle:","🪲"},
            {":bird:","🐦"},
            {":blossom:","🌼"},
            {":blowfish:","🐡"},
            {":boar:","🐗"},
            {":bouquet:","💐"},
            {":bug:","🐛"},
            {":cactus:","🌵"},
            {":camel:","🐫"},
            {":cat:","🐱"},
            {":cat2:","🐈"},
            {":cherry blossom:","🌸"},
            {":chestnut:","🌰"},
            {":chicken:","🐔"},
            {":chipmunk:","🐿️"},
            {":cloud:","☁"},
            {":cloud with lightning and rain:","⛈️"},
            {":comet:","☄️"},
            {":cow:","🐮"},
            {":cow2:","🐄"},
            {":crab:","🦀"},
            {":crescent moon:","🌙"},
            {":crocodile:","🐊"},
            {":cyclone:","🌀"},
            {":deciduous tree:","🌳"},
            {":dodo:","🦤"},
            {":dog:","🐶"},
            {":dog2:","🐕"},
            {":dolphin:","🐬"},
            {":donkey:","🫏"},
            {":dragon face:","🐲"},
            {":dragon:","🐉"},
            {":dromedary camel:","🐪"},
            {":eagle:","🦅"},
            {":ear of rice:","🌾"},
            {":earth africa:","🌍"},
            {":earth americas:","🌎"},
            {":earth asia:","🌏"},
            {":elephant:","🐘"},
            {":evergreen tree:","🌲"},
            {":fallen leaf:","🍂"},
            {":feather:","🪶"},
            {":first quarter moon with face:","🌛"},
            {":first quarter moon:","🌓"},
            {":fish:","🐟"},
            {":fly:","🪰"},
            {":foggy:","🌁"},
            {":four leaf clover:","🍀"},
            {":frog:","🐸"},
            {":full moon with face:","🌝"},
            {":full moon:","🌕"},
            {":giraffe:","🦒"},
            {":globe with meridians:","🌐"},
            {":goat:","🐐"},
            {":goose:","🪿"},
            {":hamster:","🐹"},
            {":hatched chick:","🐥"},
            {":hatching chick:","🐣"},
            {":herb:","🌿"},
            {":hibiscus:","🌺"},
            {":honeybee:","🐝"},
            {":horse:","🐴"},
            {":hyacinth:","🪻"},
            {":ice:","🧊"},
            {":kangaroo:","🦘"},
            {":koala:","🐨"},
            {":last quarter moon with face:","🌜"},
            {":last quarter moon:","🌗"},
            {":leafless tree:","🪾"},
            {":leaves:","🍃"},
            {":leopard:","🐆"},
            {":lotus:","🪷"},
            {":mammoth:","🦣"},
            {":maple leaf:","🍁"},
            {":milky way:","🌌"},
            {":monkey face:","🐵"},
            {":monkey:","🐒"},
            {":moon:","🌔"},
            {":moose:","🫎"},
            {":mouse:","🐭"},
            {":mouse2:","🐁"},
            {":mushroom:","🍄"},
            {":nest with eggs:","🪺"},
            {":new moon with face:","🌚"},
            {":new moon:","🌑"},
            {":ocean:","🌊"},
            {":octopus:","🐙"},
            {":ox:","🐂"},
            {":oyster:","🦪"},
            {":palm tree:","🌴"},
            {":panda face:","🐼"},
            {":partly sunny:","⛅"},
            {":paw prints:","🐾"},
            {":penguin:","🐧"},
            {":pig nose:","🐽"},
            {":pig:","🐷"},
            {":pig2:","🐖"},
            {":poodle:","🐩"},
            {":rabbit:","🐰"},
            {":rabbit2:","🐇"},
            {":racehorse:","🐎"},
            {":ram:","🐏"},
            {":rat:","🐀"},
            {":rooster:","🐓"},
            {":rose:","🌹"},
            {":rosette:","🏵️"},
            {":seal:","🦭"},
            {":seedling:","🌱"},
            {":shamrock:","☘️"},
            {":sheep:","🐑"},
            {":shell:","🐚"},
            {":sloth:","🦥"},
            {":snail:","🐌"},
            {":snake:","🐍"},
            {":snowflake:","❄"},
            {":snowman:","⛄"},
            {":squid:","🦑"},
            {":star and crescent:","☪️"},
            {":sun behind small cloud:","🌤️"},
            {":sun with face:","🌞"},
            {":sunflower:","🌻"},
            {":sunny:","☀"},
            {":swan:","🦢"},
            {":thermometer:","🌡️"},
            {":tiger:","🐯"},
            {":tiger2:","🐅"},
            {":tropical fish:","🐠"},
            {":tulip:","🌷"},
            {":turtle:","🐢"},
            {":umbrella:","☔"},
            {":unicorn:","🦄"},
            {":volcano:","🌋"},
            {":waning crescent moon:","🌘"},
            {":waning gibbous moon:","🌖"},
            {":water buffalo:","🐃"},
            {":waxing crescent moon:","🌒"},
            {":waxing gibbous moon:","🌔"},
            {":whale:","🐳"},
            {":whale2:","🐋"},
            {":wilted flower:","🥀"},
            {":wing:","🪽"},
            {":wolf:","🐺"},
            {":zap:","⚡"},
        };

        public static Dictionary<string, string> Objects = new() 
        {
            {":1st place medal:","🥇"},
            {":8ball:","🎱"},
            {":admission tickets:","🎟️"},
            {":alarm clock:","⏰"},
            {":alembic:","⚗️"},
            {":anatomical heart:","🫀"},
            {":apple:","🍎"},
            {":art:","🎨"},
            {":baby bottle:","🍼"},
            {":badminton:","🏸"},
            {":balance scale:","⚖️"},
            {":ballet shoes:","🩰"},
            {":balloon:","🎈"},
            {":ballot box with ballot:","🗳️"},
            {":bamboo:","🎍"},
            {":banana:","🍌"},
            {":banjo:","🪕"},
            {":bar chart:","📊"},
            {":baseball:","⚾"},
            {":basketball:","🏀"},
            {":bath:","🛀"},
            {":bathtub:","🛁"},
            {":battery:","🔋"},
            {":bed:","🛏️"},
            {":beer:","🍺"},
            {":beers:","🍻"},
            {":bell:","🔔"},
            {":bento:","🍱"},
            {":beverage box:","🧃"},
            {":bicyclist:","🚴"},
            {":bikini:","👙"},
            {":birthday:","🎂"},
            {":black joker:","🃏"},
            {":black nib:","✒"},
            {":blue book:","📘"},
            {":blueberries:","🫐"},
            {":bomb:","💣"},
            {":book:","📖"},
            {":bookmark tabs:","📑"},
            {":bookmark:","🔖"},
            {":books:","📚"},
            {":boomerang:","🪃"},
            {":boot:","👢"},
            {":bottle with popping cork:","🍾"},
            {":bowling:","🎳"},
            {":bread:","🍞"},
            {":briefcase:","💼"},
            {":bubble tea:","🧋"},
            {":bubbles:","🫧"},
            {":bulb:","💡"},
            {":burrito:","🌯"},
            {":cake:","🍰"},
            {":calendar:","📆"},
            {":calling:","📲"},
            {":camera:","📷"},
            {":camera with flash:","📸"},
            {":candle:","🕯️"},
            {":candy:","🍬"},
            {":canned food:","🥫"},
            {":card index:","📇"},
            {":cd:","💿"},
            {":chains:","⛓️"},
            {":chart with downwards trend:","📉"},
            {":chart with upwards trend:","📈"},
            {":cheese wedge:","🧀"},
            {":cherries:","🍒"},
            {":chocolate bar:","🍫"},
            {":christmas tree:","🎄"},
            {":clamp:","🗜️"},
            {":clapper:","🎬"},
            {":clipboard:","📋"},
            {":closed book:","📕"},
            {":closed lock with key:","🔐"},
            {":closed umbrella:","🌂"},
            {":clubs:","♣"},
            {":cocktail:","🍸"},
            {":coffee:","☕"},
            {":coffin:","⚰️"},
            {":computer:","💻"},
            {":computer mouse:","🖱️"},
            {":confetti ball:","🎊"},
            {":control knobs:","🎛️"},
            {":cookie:","🍪"},
            {":corn:","🌽"},
            {":couch and lamp:","🛋️"},
            {":crayon:","🖍️"},
            {":credit card:","💳"},
            {":cricket:","🦗"},
            {":cricket game:","🏏"},
            {":croissant:","🥐"},
            {":crossed swords:","⚔️"},
            {":crown:","👑"},
            {":crutch:","🩼"},
            {":crystal ball:","🔮"},
            {":cupcake:","🧁"},
            {":curling stone:","🥌"},
            {":curly loop:","➰"},
            {":curry:","🍛"},
            {":custard:","🍮"},
            {":dagger:","🗡️"},
            {":dango:","🍡"},
            {":dart:","🎯"},
            {":date:","📅"},
            {":desktop computer:","🖥️"},
            {":diamonds:","♦"},
            {":diving mask:","🤿"},
            {":dollar:","💵"},
            {":dolls:","🎎"},
            {":door:","🚪"},
            {":doughnut:","🍩"},
            {":dove:","🕊️"},
            {":dress:","👗"},
            {":drop of blood:","🩸"},
            {":dumpling:","🥟"},
            {":dvd:","📀"},
            {":egg:","🥚"},
            {":eggplant:","🍆"},
            {":electric plug:","🔌"},
            {":email:","📧"},
            {":e-mail:","📧"},
            {":envelope:","✉"},
            {":euro:","💶"},
            {":exploding head:","🤯"},
            {":eyeglasses:","👓"},
            {":fax:","📠"},
            {":ferry:","⛴️"},
            {":file cabinet:","🗄️"},
            {":file folder:","📁"},
            {":film frames:","🎞️"},
            {":film projector:","📽️"},
            {":fireworks:","🎆"},
            {":fish cake:","🍥"},
            {":fishing pole and fish:","🎣"},
            {":flags:","🎏"},
            {":flashlight:","🔦"},
            {":flat shoe:","🥿"},
            {":floppy disk:","💾"},
            {":flower playing cards:","🎴"},
            {":flute:","🪈"},
            {":flying disc:","🥏"},
            {":folding hand fan:","🪭"},
            {":football:","🏈"},
            {":fork and knife:","🍴"},
            {":fork and knife with plate:","🍽️"},
            {":framed picture:","🖼️"},
            {":fried shrimp:","🍤"},
            {":fries:","🍟"},
            {":funeral urn:","⚱️"},
            {":game die:","🎲"},
            {":gear:","⚙️"},
            {":gem:","💎"},
            {":ghost:","👻"},
            {":gift heart:","💝"},
            {":gift:","🎁"},
            {":ginger root:","🫚"},
            {":goal net:","🥅"},
            {":golf:","⛳"},
            {":grapes:","🍇"},
            {":green apple:","🍏"},
            {":green book:","📗"},
            {":guide dog:","🦮"},
            {":guitar:","🎸"},
            {":gun:","🔫"},
            {":hamburger:","🍔"},
            {":hammer:","🔨"},
            {":hammer and pick:","⚒️"},
            {":hammer and wrench:","🛠️"},
            {":handbag:","👜"},
            {":harp:","🪉"},
            {":headphones:","🎧"},
            {":hearts:","♥"},
            {":high brightness:","🔆"},
            {":high heel:","👠"},
            {":hocho:","🔪"},
            {":hole:","🕳️"},
            {":honey pot:","🍯"},
            {":horse racing:","🏇"},
            {":hot dog:","🌭"},
            {":hot pepper:","🌶️"},
            {":hourglass flowing sand:","⏳"},
            {":hourglass:","⌛"},
            {":ice cream:","🍨"},
            {":icecream:","🍦"},
            {":inbox tray:","📥"},
            {":incoming envelope:","📨"},
            {":iphone:","📱"},
            {":jack o lantern:","🎃"},
            {":jar:","🫙"},
            {":jeans:","👖"},
            {":joystick:","🕹️"},
            {":kaaba:","🕋"},
            {":key:","🔑"},
            {":keyboard:","⌨️"},
            {":kimono:","👘"},
            {":lab coat:","🥼"},
            {":label:","🏷️"},
            {":lacrosse:","🥍"},
            {":leafy green:","🥬"},
            {":ledger:","📒"},
            {":left speech bubble:","🗨️"},
            {":lemon:","🍋"},
            {":linked paperclips:","🖇️"},
            {":lipstick:","💄"},
            {":lock with ink pen:","🔏"},
            {":lock:","🔒"},
            {":lollipop:","🍭"},
            {":loop:","➿"},
            {":loudspeaker:","📢"},
            {":low brightness:","🔅"},
            {":mag right:","🔎"},
            {":mag:","🔍"},
            {":mahjong:","🀄"},
            {":mailbox closed:","📪"},
            {":mailbox with mail:","📬"},
            {":mailbox with no mail:","📭"},
            {":mailbox:","📫"},
            {":mans shoe:","👞"},
            {":mantelpiece clock:","🕰️"},
            {":maracas:","🪇"},
            {":martial arts uniform:","🥋"},
            {":meat on bone:","🍖"},
            {":mega:","📣"},
            {":melon:","🍈"},
            {":memo:","📝"},
            {":menorah:","🕎"},
            {":microphone:","🎤"},
            {":microscope:","🔬"},
            {":military helmet:","🪖"},
            {":military medal:","🎖️"},
            {":minidisc:","💽"},
            {":mirror ball:","🪩"},
            {":money with wings:","💸"},
            {":moneybag:","💰"},
            {":mortar board:","🎓"},
            {":mountain bicyclist:","🚵"},
            {":movie camera:","🎥"},
            {":musical keyboard:","🎹"},
            {":musical score:","🎼"},
            {":mute:","🔇"},
            {":name badge:","📛"},
            {":nazar amulet:","🧿"},
            {":necktie:","👔"},
            {":nesting dolls:","🪆"},
            {":newspaper:","📰"},
            {":no bell:","🔕"},
            {":notebook with decorative cover:","📔"},
            {":notebook:","📓"},
            {":nut and bolt:","🔩"},
            {":oden:","🍢"},
            {":open file folder:","📂"},
            {":orange book:","📙"},
            {":outbox tray:","📤"},
            {":page facing up:","📄"},
            {":page with curl:","📃"},
            {":pager:","📟"},
            {":pancakes:","🥞"},
            {":paperclip:","📎"},
            {":parachute:","🪂"},
            {":partying face:","🥳"},
            {":pea pod:","🫛"},
            {":peach:","🍑"},
            {":pear:","🍐"},
            {":pen:","🖊️"},
            {":pencil:","📝"},
            {":pencil2:","✏"},
            {":people wrestling:","🤼"},
            {":phone:","☎"},
            {":pick:","⛏️"},
            {":pill:","💊"},
            {":pineapple:","🍍"},
            {":ping pong:","🏓"},
            {":pizza:","🍕"},
            {":playground slide:","🛝"},
            {":popcorn:","🍿"},
            {":postal horn:","📯"},
            {":postbox:","📮"},
            {":pouch:","👝"},
            {":poultry leg:","🍗"},
            {":pound:","💷"},
            {":pouring liquid:","🫗"},
            {":prayer beads:","📿"},
            {":printer:","🖨️"},
            {":purse:","👛"},
            {":pushpin:","📌"},
            {":radio:","📻"},
            {":ramen:","🍜"},
            {":red envelope:","🧧"},
            {":red hair:","🦰"},
            {":reminder ribbon:","🎗️"},
            {":rescue worker’s helmet:","⛑️"},
            {":ribbon:","🎀"},
            {":rice ball:","🍙"},
            {":rice cracker:","🍘"},
            {":rice scene:","🎑"},
            {":rice:","🍚"},
            {":right anger bubble:","🗯️"},
            {":ring:","💍"},
            {":ring buoy:","🛟"},
            {":ringed planet:","🪐"},
            {":rock:","🪨"},
            {":rolled-up newspaper:","🗞️"},
            {":roller skate:","🛼"},
            {":root vegetable:","🫜"},
            {":rugby football:","🏉"},
            {":running shirt with sash:","🎽"},
            {":safety vest:","🦺"},
            {":sake:","🍶"},
            {":salt:","🧂"},
            {":sandal:","👡"},
            {":santa:","🎅"},
            {":sari:","🥻"},
            {":satellite:","📡"},
            {":saxophone:","🎷"},
            {":school satchel:","🎒"},
            {":scissors:","✂"},
            {":scroll:","📜"},
            {":seat:","💺"},
            {":shaved ice:","🍧"},
            {":shirt:","👕"},
            {":shoe:","👞"},
            {":shopping bags:","🛍️"},
            {":shopping cart:","🛒"},
            {":shorts:","🩳"},
            {":shovel:","🪏"},
            {":shower:","🚿"},
            {":skateboard:","🛹"},
            {":ski:","🎿"},
            {":skier:","⛷️"},
            {":sled:","🛷"},
            {":smoking:","🚬"},
            {":snowboarder:","🏂"},
            {":soccer:","⚽"},
            {":socks:","🧦"},
            {":sound:","🔉"},
            {":space invader:","👾"},
            {":spades:","♠"},
            {":spaghetti:","🍝"},
            {":sparkler:","🎇"},
            {":speaker:","🔈"},
            {":speaker high volume:","🔊"},
            {":speaking head:","🗣️"},
            {":spiral calendar:","🗓️"},
            {":splatter:","🫟"},
            {":sports medal:","🏅"},
            {":stethoscope:","🩺"},
            {":stew:","🍲"},
            {":stopwatch:","⏱️"},
            {":straight ruler:","📏"},
            {":strawberry:","🍓"},
            {":studio microphone:","🎙️"},
            {":surfer:","🏄"},
            {":sushi:","🍣"},
            {":sweet potato:","🍠"},
            {":swimmer:","🏊"},
            {":syringe:","💉"},
            {":tada:","🎉"},
            {":tanabata tree:","🎋"},
            {":tangerine:","🍊"},
            {":tea:","🍵"},
            {":teapot:","🫖"},
            {":telephone receiver:","📞"},
            {":telephone:","☎"},
            {":telescope:","🔭"},
            {":tennis:","🎾"},
            {":thong sandal:","🩴"},
            {":timer clock:","⏲️"},
            {":toilet:","🚽"},
            {":tomato:","🍅"},
            {":tophat:","🎩"},
            {":trackball:","🖲️"},
            {":triangular ruler:","📐"},
            {":trophy:","🏆"},
            {":tropical drink:","🍹"},
            {":trumpet:","🎺"},
            {":tshirt:","👕"},
            {":tv:","📺"},
            {":umbrella on ground:","⛱️"},
            {":unlock:","🔓"},
            {":vhs:","📼"},
            {":video camera:","📹"},
            {":video game:","🎮"},
            {":violin:","🎻"},
            {":wastebasket:","🗑️"},
            {":watch:","⌚"},
            {":watermelon:","🍉"},
            {":white cane:","🦯"},
            {":wind chime:","🎐"},
            {":wine glass:","🍷"},
            {":womans clothes:","👚"},
            {":womans hat:","👒"},
            {":wrench:","🔧"},
            {":x-ray:","🩻"},
            {":yen:","💴"},
            {":yo-yo:","🪀"},
        };

        public static Dictionary<string, string> Places = new() 
        {
            {":aerial tramway:","🚡"},
            {":airplane:","✈"},
            {":airplane arrival:","🛬"},
            {":airplane departure:","🛫"},
            {":ambulance:","🚑"},
            {":anchor:","⚓"},
            {":articulated lorry:","🚛"},
            {":atm:","🏧"},
            {":auto rickshaw:","🛺"},
            {":bank:","🏦"},
            {":barber:","💈"},
            {":beginner:","🔰"},
            {":bike:","🚲"},
            {":black flag:","🏴"},
            {":blue car:","🚙"},
            {":boat:","⛵"},
            {":bridge at night:","🌉"},
            {":bullettrain front:","🚅"},
            {":bullettrain side:","🚄"},
            {":bus:","🚌"},
            {":busstop:","🚏"},
            {":canoe:","🛶"},
            {":car:","🚗"},
            {":carousel horse:","🎠"},
            {":checkered flag:","🏁"},
            {":church:","⛪"},
            {":circus tent:","🎪"},
            {":city sunrise:","🌇"},
            {":city sunset:","🌆"},
            {":construction:","🚧"},
            {":convenience store:","🏪"},
            {":crossed flags:","🎌"},
            {":department store:","🏬"},
            {":elevator:","🛗"},
            {":european castle:","🏰"},
            {":european post office:","🏤"},
            {":factory:","🏭"},
            {":ferris wheel:","🎡"},
            {":fire engine:","🚒"},
            {":flying saucer:","🛸"},
            {":fountain:","⛲"},
            {":fuelpump:","⛽"},
            {":helicopter:","🚁"},
            {":hindu temple:","🛕"},
            {":hospital:","🏥"},
            {":hotel:","🏨"},
            {":hotsprings:","♨"},
            {":house with garden:","🏡"},
            {":house:","🏠"},
            {":hut:","🛖"},
            {":izakaya lantern:","🏮"},
            {":japan:","🗾"},
            {":japanese castle:","🏯"},
            {":kick scooter:","🛴"},
            {":light rail:","🚈"},
            {":love hotel:","🏩"},
            {":minibus:","🚐"},
            {":monorail:","🚝"},
            {":motor boat:","🛥️"},
            {":mount fuji:","🗻"},
            {":mountain:","⛰️"},
            {":mountain cableway:","🚠"},
            {":mountain railway:","🚞"},
            {":moyai:","🗿"},
            {":office:","🏢"},
            {":oncoming automobile:","🚘"},
            {":oncoming bus:","🚍"},
            {":oncoming police car:","🚔"},
            {":oncoming taxi:","🚖"},
            {":passenger ship:","🛳️"},
            {":performing arts:","🎭"},
            {":pickup truck:","🛻"},
            {":place of worship:","🛐"},
            {":police car:","🚓"},
            {":post office:","🏣"},
            {":racing car:","🏎️"},
            {":railway car:","🚃"},
            {":rainbow:","🌈"},
            {":red car:","🚗"},
            {":rocket:","🚀"},
            {":roller coaster:","🎢"},
            {":rotating light:","🚨"},
            {":round pushpin:","📍"},
            {":rowboat:","🚣"},
            {":sailboat:","⛵"},
            {":school:","🏫"},
            {":shinto shrine:","⛩️"},
            {":ship:","🚢"},
            {":slot machine:","🎰"},
            {":small airplane:","🛩️"},
            {":snow-capped mountain:","🏔️"},
            {":speedboat:","🚤"},
            {":stadium:","🏟️"},
            {":stars:","🌠"},
            {":station:","🚉"},
            {":statue of liberty:","🗽"},
            {":steam locomotive:","🚂"},
            {":sunrise over mountains:","🌄"},
            {":sunrise:","🌅"},
            {":suspension railway:","🚟"},
            {":taxi:","🚕"},
            {":tent:","⛺"},
            {":ticket:","🎫"},
            {":tokyo tower:","🗼"},
            {":tractor:","🚜"},
            {":traffic light:","🚥"},
            {":train:","🚋"},
            {":train2:","🚆"},
            {":tram:","🚊"},
            {":triangular flag on post:","🚩"},
            {":trolleybus:","🚎"},
            {":truck:","🚚"},
            {":vertical traffic light:","🚦"},
            {":warning:","⚠"},
            {":wedding:","💒"},
            {":white flag:","🏳️"},
            {":world map:","🗺️"},
        };

        public static Dictionary<string, string> Symbols = new() 
        {
            {":100:","💯"},
            {":1234:","🔢"},
            {":a:","🅰"},
            {":ab:","🆎"},
            {":abc:","🔤"},
            {":abcd:","🔡"},
            {":accept:","🉑"},
            {":aquarius:","♒"},
            {":aries:","♈:"},
            {":arrow backward:","◀️"},
            {":arrow double down:","⏬"},
            {":arrow down small:","🔽"},
            {":arrow down:","⬇️"},
            {":arrow forward:","▶️"},
            {":arrow heading down:","⤵️"},
            {":arrow heading up:","⤴️"},
            {":arrow left:","⬅️"},
            {":arrow lower left:","↙️"},
            {":arrow lower right:","↘️"},
            {":arrow right hook:","↪️"},
            {":arrow right:","➡️"},
            {":arrow up down:","↕️"},
            {":arrow up small:","🔼"},
            {":arrow up:","⬆️"},
            {":arrow upper left:","↖️"},
            {":arrow upper right:","↗️"},
            {":arrows clockwise:","🔃"},
            {":arrows counterclockwise:","🔄"},
            {":atom symbol:","⚛️"},
            {":b:","🅱"},
            {":baby symbol:","🚼"},
            {":baggage claim:","🛄"},
            {":ballot box with check:","☑️"},
            {":bangbang:","‼️"},
            {":biohazard:","☣️"},
            {":black circle:","⚫"},
            {":black heart:","🖤"},
            {":black large square:","⬛"},
            {":black medium-small square:","◾"},
            {":black small square:","▪️"},
            {":black square button:","🔲"},
            {":brown square:","🟫"},
            {":cancer:","♋"},
            {":capital abcd:","🔠"},
            {":capricorn:","♑"},
            {":card index dividers:","🗂️"},
            {":chart:","💹"},
            {":check mark button:","✅"},
            {":chess pawn:","♟️"},
            {":children crossing:","🚸"},
            {":cinema:","🎦"},
            {":cl:","🆑"},
            {":clock1:","🕐"},
            {":clock10:","🕙"},
            {":clock1030:","🕥"},
            {":clock11:","🕚"},
            {":clock1130:","🕦"},
            {":clock12:","🕛"},
            {":clock1230:","🕧"},
            {":clock130:","🕜"},
            {":clock2:","🕑"},
            {":clock230:","🕝"},
            {":clock3:","🕒"},
            {":clock330:","🕞"},
            {":clock4:","🕓"},
            {":clock430:","🕟"},
            {":clock5:","🕔"},
            {":clock530:","🕠"},
            {":clock6:","🕕"},
            {":clock630:","🕡"},
            {":clock7:","🕖"},
            {":clock730:","🕢"},
            {":clock8:","🕗"},
            {":clock830:","🕣"},
            {":clock9:","🕘"},
            {":clock930:","🕤"},
            {":congratulations:","㊗️"},
            {":cool:","🆒"},
            {":copyright:","©️"},
            {":currency exchange:","💱"},
            {":customs:","🛃"},
            {":diamond shape with a dot inside:","💠"},
            {":do not litter:","🚯"},
            {":eight pointed black star:","✴️"},
            {":eight spoked asterisk:","✳️"},
            {":eight:","8️⃣"},
            {":eject button:","⏏️"},
            {":end:","🔚"},
            {":fast forward:","⏩"},
            {":female sign:","♀️"},
            {":five:","5️⃣"},
            {":fleur-de-lis:","⚜️"},
            {":four:","4️⃣"},
            {":free:","🆓"},
            {":gemini:","♊"},
            {":hamsa:","🪬"},
            {":hash:","#️⃣"},
            {":heart decoration:","💟"},
            {":heart exclamation:","❣️"},
            {":heavy check mark:","✔️"},
            {":heavy division sign:","➗"},
            {":heavy dollar sign:","💲"},
            {":heavy equals sign:","🟰"},
            {":heavy exclamation mark:","❗"},
            {":heavy minus sign:","➖"},
            {":heavy multiplication x:","✖️"},
            {":id:","🆔"},
            {":ideograph advantage:","🉐"},
            {":infinity:","♾️"},
            {":information source:","ℹ️"},
            {":interrobang:","⁉️"},
            {":keycap ten:","🔟"},
            {":khanda:","🪯"},
            {":koko:","🈁"},
            {":large blue circle:","🔵"},
            {":large blue diamond:","🔷"},
            {":large orange diamond:","🔶"},
            {":last track button:","⏮️"},
            {":latin cross:","✝️"},
            {":left luggage:","🛅"},
            {":left right arrow:","↔️"},
            {":leftwards arrow with hook:","↩️"},
            {":leo:","♌"},
            {":libra:","♎"},
            {":light blue heart:","🩵"},
            {":link:","🔗"},
            {":m:","Ⓜ️"},
            {":male sign:","♂️"},
            {":medical symbol:","⚕️"},
            {":mens:","🚹"},
            {":metro:","🚇"},
            {":mobile phone off:","📴"},
            {":negative squared cross mark:","❎"},
            {":new:","🆕"},
            {":next track button:","⏭️"},
            {":ng:","🆖"},
            {":nine:","9️⃣"},
            {":no bicycles:","🚳"},
            {":no entry:","⛔"},
            {":no entry sign:","🚫"},
            {":no mobile phones:","📵"},
            {":no pedestrians:","🚷"},
            {":no smoking:","🚭"},
            {":non-potable water:","🚱"},
            {":o:","⭕"},
            {":o2:","🅾"},
            {":ok:","🆗"},
            {":om:","🕉️"},
            {":on:","🔛"},
            {":one:","1️⃣"},
            {":ophiuchus:","⛎"},
            {":orange circle:","🟠"},
            {":orthodox cross:","☦️"},
            {":parking:","🅿"},
            {":part alternation mark:","〽️"},
            {":passport control:","🛂"},
            {":pause button:","⏸️"},
            {":peace symbol:","☮️"},
            {":pink heart:","🩷"},
            {":pisces:","♓"},
            {":play or pause button:","⏯️"},
            {":plus:","➕"},
            {":potable water:","🚰"},
            {":put litter in its place:","🚮"},
            {":radio button:","🔘"},
            {":radioactive:","☢️"},
            {":record button:","⏺️"},
            {":recycle:","♻️"},
            {":red circle:","🔴"},
            {":registered:","®️"},
            {":repeat one:","🔂"},
            {":repeat:","🔁"},
            {":restroom:","🚻"},
            {":rewind:","⏪"},
            {":sa:","🈂"},
            {":sagittarius:","♐"},
            {":scorpius:","♏"},
            {":secret:","㊙️"},
            {":seven:","7️⃣"},
            {":signal strength:","📶"},
            {":six pointed star:","🔯"},
            {":six:","6️⃣"},
            {":small blue diamond:","🔹"},
            {":small orange diamond:","🔸"},
            {":small red triangle down:","🔻"},
            {":small red triangle:","🔺"},
            {":soon:","🔜"},
            {":sos:","🆘"},
            {":sparkle:","❇️"},
            {":star of david:","✡️"},
            {":stop sign:","🛑"},
            {":symbols:","🔣"},
            {":taurus:","♉"},
            {":three:","3️⃣"},
            {":tm:","™️"},
            {":top:","🔝"},
            {":transgender symbol:","⚧️"},
            {":trident:","🔱"},
            {":twisted rightwards arrows:","🔀"},
            {":two:","2️⃣"},
            {":u5272:","🈹"},
            {":u5408:","🈴"},
            {":u55b6:","🈺"},
            {":u6307:","🈯"},
            {":u6708:","🈷"},
            {":u6709:","🈶"},
            {":u6e80:","🈵"},
            {":u7121:","🈚"},
            {":u7533:","🈸"},
            {":u7981:","🈲"},
            {":u7a7a:","🈳"},
            {":underage:","🔞"},
            {":up:","🆙"},
            {":vibration mode:","📳"},
            {":virgo:","♍"},
            {":vs:","🆚"},
            {":wavy dash:","〰️"},
            {":wc:","🚾"},
            {":wheel of dharma:","☸️"},
            {":wheelchair:","♿"},
            {":white circle:","⚪"},
            {":white flower:","💮"},
            {":white heart:","🤍"},
            {":white large square:","⬜"},
            {":white medium square:","◻️"},
            {":white medium-small square:","◽"},
            {":white small square:","▫️"},
            {":white square button:","🔳"},
            {":wireless:","🛜"},
            {":womens:","🚺"},
            {":x:","❌"},
            {":yin yang:","☯️"},
            {":zero:","0️⃣"},
            {"arrow double up:","⏫"},
            {"black circle:","⚫"},
            {"curly loop:","➰"},
            {"heavy plus sign:","➕"},
            {"hite square: :white square:",":wh"},
            {"lack square: :black square:",":bl"},
            {"no entry:","⛔"},
            {"white check mark:","✅"},
        };
    }
}
