// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EmojiSense
{
    internal sealed partial class Vsix
    {
        public const string Id = "EmojiSense.2461fd3c-53c0-4e86-a00f-52d181d4a194";
        public const string Name = "EmojiSense";
        public const string Description = @"IntelliSense for emojis in code comments and string for all languages";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "emoji, unicode, char";
    }
}
